import {
  GraduationCap,
  Shield,
  University,
  Briefcase,
  ClipboardCheck,
  Wallet,
  Salad,
  KeyRound,
  Globe,
  BookMarked,
  Compass,
  Earth,
  User,
  Monitor,
  Banknote,
  Microscope,
  MessagesSquare,
  Lightbulb,
  Dumbbell,
  BusFront,
} from "lucide-react";

const categories = [
  { name: "Academics", icon: GraduationCap, items: 15 },
  { name: "Administrative", icon: Shield, items: 15 },
  { name: "Admissions", icon: University, items: 15 },
  { name: "Careers", icon: Briefcase, items: 15 },
  { name: "Enrollment", icon: ClipboardCheck, items: 15 },
  { name: "Faculty Services", icon: User, items: 15 },
  { name: "Facilities", icon: KeyRound, items: 15 },
  { name: "Finances", icon: Wallet, items: 15 },
  { name: "Housing & Dining", icon: Salad, items: 15 },
  { name: "International", icon: Globe, items: 15 },
  { name: "IT Services", icon: Monitor, items: 15 },
  { name: "Libraries", icon: BookMarked, items: 15 },
  { name: "Orientation", icon: Compass, items: 15 },
  { name: "Payroll & Taxes", icon: Banknote, items: 15 },
  { name: "People & Culture", icon: Earth, items: 15 },
  { name: "Personal Information", icon: User, items: 15 },
  { name: "Social Media", icon: MessagesSquare, items: 15 },
  { name: "Research", icon: Microscope, items: 15 },
  { name: "Teaching & Learning", icon: Lightbulb, items: 15 },
  { name: "Training", icon: Dumbbell, items: 15 },
  { name: "Transit", icon: BusFront, items: 15 },
];

export type CategoryItem = (typeof categories)[number];

export default categories;
